---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  warning = FALSE, message = FALSE
)
```

# scatteR

<!-- badges: start -->
<!-- badges: end -->

scatteR generates scatterplots based on [scagnostic](https://cran.r-project.org/web/packages/scagnostics/index.html) measurements. The current implementation uses the GenSA package for optimization.

## Installation

You can install the released version of scatteR from [Github](https://github.com/janithwanni/scatteR) with:

``` r
install.packages("devtools")
devtools::install_github("janithwanni/scatteR")
```

## Example

```{r example}
library(scatteR)
## basic example code
df <- scatteR(measurements = c("Monotonic" = 0.9),n_points = 20,
              init_points = 4,error_var = 0.05,global_min = 0.01)
```

```{r}
library(scagnostics)
scagnostics(df)
```

```{r}
plot(df$x,df$y)
```
